package com.da.po;

import java.util.Date;
import java.util.List;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.id
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.username
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.birthday
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.sex
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.address
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    private String address;

    private List<Account> accounts;     //一对多 一个用户有多个账户

    public List<Account> getAccounts() {
        return accounts;
    }

    public void setAccounts(List<Account> accounts) {
        this.accounts = accounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.id
     *
     * @return the value of USER.id
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.id
     *
     * @param id the value for USER.id
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.username
     *
     * @return the value of USER.username
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.username
     *
     * @param username the value for USER.username
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.birthday
     *
     * @return the value of USER.birthday
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.birthday
     *
     * @param birthday the value for USER.birthday
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.sex
     *
     * @return the value of USER.sex
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.sex
     *
     * @param sex the value for USER.sex
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.address
     *
     * @return the value of USER.address
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.address
     *
     * @param address the value for USER.address
     *
     * @mbg.generated Thu Mar 14 16:20:19 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}